import React from 'react'
import { Link, graphql, useStaticQuery } from 'gatsby'
import blogStyles from './blog.module.scss'
import Layout from '../components/layout'
import Head from '../components/head'

const Blogs = () => {
  const data = useStaticQuery(graphql`
    query {
      allMarkdownRemark {
        edges {
          node {
            frontmatter {
              title
              date
            }
            fields {
              slug
            }
          }
        }
      }
    }
  `)

  return (
    <Layout>
      <Head title="Markdown Blog" />
      <section className={blogStyles.container}>
        <h1>Notes and Code Snippets</h1>
        <p>
          These pages are generated by Gatsby during the build process from
          markdown pages residing in a particular folder. Gatsby will generate a
          new static page for every markdown file that exists in that folder.
        </p>
        <p>
          These are some notes from{' '}
          <a href="https://lambdaschool.com/courses/full-stack-web-development">
            Lambda School's Full Stack Web Development Program
          </a>
          , various tutorials, courses, and my own studies. In them you will
          find links to the source code, live site examples, and code snippets
          that may be mentioned in the post.
        </p>
        <ol>
          {data.allMarkdownRemark.edges.map((post, i) => (
            <Link key={i} to={`blog/${post.node.fields.slug}`}>
              <li>
                <h2>{post.node.frontmatter.title}</h2>
                <p>{post.node.frontmatter.date}</p>
              </li>
            </Link>
          ))}
        </ol>
      </section>
    </Layout>
  )
}

export default Blogs
